# common configuration for python gitlab-ci jobs

variables:
  DEPLOY_ENVIRONMENT: "null"

include:
  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/python.gitlab-ci.yml

  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/bodc.gitlab-ci.yml

  - project:
      nocacuk/BODC/software/gitlab_runners
    ref: master
    file: v2/semver-tags.gitlab-ci.yml


# The test commands seen under the testenv section are executed.
test:
  extends:
   - .python-test

# The linting commands seen under the testenv:lint section are executed.
lint:
  extends:
   - .python-lint

build:
  extends:
   - .python-build

publish:
  extends:
    - .python-upload
  rules:
    # push to pypi for any alpha, beta, release candidate, or release
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+a\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+b\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+rc\d+$/'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d$/'
