# this environment is purely to have tox installed which can then be used
# to run the tests in a repeatable way. Other dependencies should not be added here,
# see the tox.ini file for testing related dependencies.
name: apds-pusher-tox
dependencies:
  # pin python version to project requirement
  - python=3.10
  - pip
  - pip:
    - setuptools
    - tox
    - twine
